### ISSUE TITLE
KMP support

### ISSUE THREAD

**Issue by DVDAndroid** [PatilShreyas/mutekt#10]
This library can be easily converted to a multiplatform one since it uses `kotlinx-coroutines` (with 100% multiplatform support) and KSP that can generate common code. So, it will be possible to use the same code for multiple platforms such as:

- Android
- JVM (ex: Jetbrains Compose applications)
- JS (ex: React or Jetbrains Compose applications)
- iOS (shared view model with Android)

**Comment by chipnesh** [comment]
Any news on multiplatform support? 
Is any help needed?

**Comment by PatilShreyas** [comment]
Thanks so much, @DVDAndroid for the contribution. This has been released in `v1.0.0-beta01` 😃.
