### ISSUE TITLE
ShareFlow ???

### ISSUE THREAD

**Issue by dononcharles** [PatilShreyas/mutekt#34]
Hi Mutekt Teams,
Thanks for your nice tool.
How can use SharedFlow inside Mutekt ? If i suppose i have some variables in this forms:

```kotlin
private val _xx = MutableSharedFlow(false)
val xx = _xx.asSharedFlow()

_xx.emit(true)

```
Thanks for helping me

**Comment by PatilShreyas** [comment]
I want to understand why you need SharedFlow when you can have a state?
