### ISSUE TITLE
How do you do atomic update with this ?

### ISSUE THREAD

**Issue by thegarlynch** [PatilShreyas/mutekt#9]
Like the  [reddit comment](https://www.reddit.com/r/androiddev/comments/wdi94p/comment/iimppf4/?utm_source=share&utm_medium=web2x&context=3) in this.

> This seems like it could break data invariants since it pushes updates on every data field update.
> 
> Eg if you depend on a data model being in either state A or B, now it can be both or neither since you must account for intermediary steps

**Comment by PatilShreyas** [comment]
Currently, it doesn't support updating two or more fields atomically.

**Comment by PatilShreyas** [comment]
This is being discussed in #12

**Comment by PatilShreyas** [comment]
This has been released in `v1.0.0-alpha03`.
